blockLookup = {
  // Birds
  BIRD_WHITE: { isBird: true, shape: "ball" },
  BIRD_BLACK: { isBird: true, shape: "ball" },
  BIRD_GREEN: { isBird: true, shape: "ball" },
  BIRD_RED: { isBird: true, shape: "ball" },
  BIRD_BLUE: { isBird: true, shape: "ball" },
  BIRD_YELLOW: { isBird: true, shape: "ball" },

  // Pigs
  PIG_BASIC_MEDIUM: { isPig: true, material: "pork", shape: "ball" },
  PIG_BASIC_SMALL: { isPig: true, material: "pork", shape: "ball" },
  PIG_MUSTACHE: { isPig: true, material: "pork", shape: "ball" },
  PIG_HELMET: { isPig: true, material: "pork", shape: "ball" },
  PIG_KING: { isPig: true, material: "pork", shape: "ball" },
  PIG_BASIC_BIG: { isPig: true, material: "pork", shape: "ball" },

  // Blocks:
  MISC_EXPLOSIVE_TNT: {},
  ICE_BLOCK_1X1: { material: "ice", shape: "rect", form: "block" },
  ICE_BLOCK_10X1: { material: "ice", shape: "rect", form: "block" },
  ICE_TRIANGLE_4X4: { material: "ice", shape: "poly", form: "block" },
  ICE_TRIANGLE_4X4_HOLLOW: { material: "ice", shape: "poly", form: "block" },
  ICE_BLOCK_2X1: { material: "ice", shape: "rect", form: "block" },
  ICE_BLOCK_2X2: { material: "ice", shape: "rect", form: "block" },
  ICE_BLOCK_4X1: { material: "ice", shape: "rect", form: "block" },
  ICE_BLOCK_4X2: { material: "ice", shape: "rect", form: "block" },
  ICE_BLOCK_8X1: { material: "ice", shape: "rect", form: "block" },
  ICE_CIRCLE_4X4: { material: "ice", shape: "ball", form: "block" },
  ICE_CIRCLE_2X2: { material: "ice", shape: "ball", form: "block" },
  ICE_BLOCK_4X4_HOLLOW: { material: "ice", shape: "rect", form: "block" },
  STONE_BLOCK_1X1: { material: "stone", shape: "rect", form: "block" },
  STONE_BLOCK_10X1: { material: "stone", shape: "rect", form: "block" },
  STONE_TRIANGLE_4X4: { material: "stone", shape: "poly", form: "block" },
  STONE_TRIANGLE_4X4_HOLLOW: {
    material: "stone",
    shape: "poly",
    form: "block",
  },
  STONE_BLOCK_2X1: { material: "stone", shape: "rect", form: "block" },
  STONE_BLOCK_2X2: { material: "stone", shape: "rect", form: "block" },
  STONE_BLOCK_4X1: { material: "stone", shape: "rect", form: "block" },
  STONE_BLOCK_4X2: { material: "stone", shape: "rect", form: "block" },
  STONE_BLOCK_8X1: { material: "stone", shape: "rect", form: "block" },
  STONE_CIRCLE_4X4: { material: "stone", shape: "ball", form: "block" },
  STONE_CIRCLE_2X2: { material: "stone", shape: "ball", form: "block" },
  STONE_BLOCK_4X4_HOLLOW: { material: "stone", shape: "rect", form: "block" },
  WOOD_BLOCK_1X1: { material: "wood", shape: "rect", form: "block" },
  WOOD_BLOCK_10X1: { material: "wood", shape: "rect", form: "block" },
  WOOD_TRIANGLE_4X4: { material: "wood", shape: "poly", form: "block" },
  WOOD_TRIANGLE_4X4_HOLLOW: { material: "wood", shape: "poly", form: "block" },
  WOOD_BLOCK_2X1: { material: "wood", shape: "rect", form: "block" },
  WOOD_BLOCK_2X2: { material: "wood", shape: "rect", form: "block" },
  WOOD_BLOCK_4X1: { material: "wood", shape: "rect", form: "block" },
  WOOD_BLOCK_4X2: { material: "wood", shape: "rect", form: "block" },
  WOOD_BLOCK_8X1: { material: "wood", shape: "rect", form: "block" },
  WOOD_CIRCLE_4X4: { material: "wood", shape: "ball", form: "block" },
  WOOD_CIRCLE_2X2: { material: "wood", shape: "ball", form: "block" },
  WOOD_BLOCK_4X4_HOLLOW: { material: "wood", shape: "rect", form: "block" },
}
